custodian_enabled: true
vasp_parallel_cmd: $VASP_PARALLEL_CMD
vasp_cmd: vasp_std
vasp_gamma_cmd: vasp_gam
vtst_swaps: false
max_errors: 5
scratch_dir: null
handlers:
  - VaspErrorHandler
  - MeshSymmetryErrorHandler
  - UnconvergedErrorHandler
  - NonConvergingErrorHandler
  - PotimErrorHandler
  - PositiveEnergyErrorHandler
  - FrozenJobErrorHandler
  - StdErrHandler
  - LargeSigmaHandler
  - IncorrectSmearingHandler
validators:
  - VasprunXMLValidator
  - VaspFilesValidator
custodian_wall_time: null
vasp_job_kwargs: null
custodian_kwargs: null
